"""empty message

Revision ID: 593f7b91ca15
Revises: 4584edaade4d
Create Date: 2024-02-25 15:46:07.537354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593f7b91ca15'
down_revision = '4584edaade4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
